### ISSUE TITLE
CimSession.Create(null) does not work on Windows 7 (x86)

### ISSUE THREAD

**Issue by natnan** [PowerShell/MMI#43]
Perhaps this is expected. It's hard to find any information about that.

My goal is to get some WMI information out of Windows. [System.Management is considered legacy apparently and does not work well with .NET Core when you don't have unspecified version of .NET Framework installed.](https://github.com/dotnet/corefx/issues/37949) And the recommended way is to utilize MMI.

It works fine on Windows 10 now but Windows 7 (x86 though not necessarily relevant) fails with not much to go on.
```
CimSession.Create(null);

Microsoft.Management.Infrastructure.CimException: FAILED
   at Microsoft.Management.Infrastructure.CimException.ThrowIfMiResultFailure(MiResult result, String errorMessage, InstanceHandle errorData)
   at Microsoft.Management.Infrastructure.CimException.ThrowIfMiResultFailure(MiResult result, InstanceHandle errorData)
   at Microsoft.Management.Infrastructure.CimSession.Create(String computerName, CimSessionOptions sessionOptions)
   at Microsoft.Management.Infrastructure.CimSession.Create(String computerName)
```

Tried both 1.0.0 and 2.0.0-preview2

**Comment by shazha** [comment]
You need [Windows Management Framework 3.0](https://www.microsoft.com/en-us/download/details.aspx?id=34595) be installed on Windows 7 SP1. please install .Net Framework 4.0 first as it's required by WMF 3.0.

**Comment by natnan** [comment]
Right. That is not very ideal as the use case is just simple information gathering from the local system (productid, Windows version etc.) that should ideally be available without installing extra management frameworks. It's especially difficult when it's a desktop application requiring the information where adding such requirements is an overkill.

I understand the requirement from MMI perspective though, and it that's the way it is, feel free to close the issue.

Thanks.

**Comment by valeriob** [comment]
Hi,
i'm having the same problem, even after i've installed the Windows Management Framework 3.0 on a windows 7 SP1 x64.
The problem is that it's a windows 7 embedded , peraps there is some more requirement needed ?
Thanks
